name: dual-encoding-system
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.0
  - torchvision=0.13
  - pytorch-cuda=11.7
  - numpy=1.23
  - tqdm=4.65
  - pyyaml=6.0
  - pip=23.0.1
  - pip:
    - nltk==3.8
